ADD https://raw.githubusercontent.com/percona/mongodb_exporter/main/LICENSE /opt/bitnami/mongodb-exporter/licenses/LICENSE
COPY --link --from=mongodb-exporter /mongodb_exporter /opt/bitnami/mongodb-exporter/bin/
