RUN install_packages mariadb-server-10.3 \
    && mkdir -p /opt/bitnami/mariadb/bin \
    && mkdir -p /opt/bitnami/mariadb/sbin \
    && mkdir -p /opt/bitnami/mariadb/lib \
    && ln -s /usr/bin/my* /opt/bitnami/mariadb/bin/ \
    && ln -s /usr/sbin/my* /opt/bitnami/mariadb/sbin/ \
    && ln -s /usr/bin/maria* /opt/bitnami/mariadb/bin/ \
    && ln -s /usr/sbin/maria* /opt/bitnami/mariadb/sbin/ \
    && ln -s /usr/lib/x86_64-linux-gnu/mariadb19/plugin /opt/bitnami/mariadb/plugin
