ADD https://raw.githubusercontent.com/prometheus/mysqld_exporter/master/LICENSE /opt/bitnami/consul-exporter/licenses/LICENSE
COPY --link --from=mysqld-exporter /bin/mysqld_exporter /opt/bitnami/mysqld-exporter/bin/
