ADD https://raw.githubusercontent.com/jetstack/cert-manager/master/LICENSE /opt/bitnami/cert-manager/licenses/LICENSE
COPY --from=cert-manager /app/cmd/controller/controller /opt/bitnami/cert-manager/bin/cert-manager
