RUN install_packages curl ca-certificates \
 && mkdir -p /opt/bitnami/cert-manager/licenses \
 && curl -L -o /opt/bitnami/cert-manager/licenses/LICENSE \
    https://raw.githubusercontent.com/jetstack/cert-manager/master/LICENSE

COPY --from=cert-manager /app/cmd/controller/controller /opt/bitnami/cert-manager/bin/cert-manager
