RUN install_packages curl ca-certificates \
 && mkdir -p /opt/bitnami/consul-exporter/licenses \
 && curl -L -o /opt/bitnami/consul-exporter/licenses/LICENSE \
    https://raw.githubusercontent.com/prometheus/consul_exporter/master/LICENSE

COPY --from=consul-exporter /bin/consul_exporter /opt/bitnami/consul-exporter/bin/
