ADD https://raw.githubusercontent.com/consul/consul/master/LICENSE-AGPLv3.txt /opt/bitnami/minio-client/licenses/LICENSE-AGPLv3.txt
COPY --from=minio-client /bin/consul /opt/bitnami/consul/bin/consul
