RUN install_packages curl ca-certificates \
 && mkdir -p /opt/bitnami/consul/licenses \
 && curl -L -o /opt/bitnami/consul/licenses/LICENSE \
    https://raw.githubusercontent.com/consul/consul/master/LICENSE-AGPLv3.txt

COPY --from=hashicorp/consul:{{{VERSION}}} /bin/consul /opt/bitnami/consul/bin/consul
