RUN install_packages curl ca-certificates \
 && mkdir -p /opt/bitnami/acmesolver/licenses \
 && curl -L -o /opt/bitnami/acmesolver/licenses/LICENSE \
    https://raw.githubusercontent.com/jetstack/cert-manager/master/LICENSE

COPY --from=acmesolver /app/cmd/acmesolver/acmesolver /opt/bitnami/acmesolver/bin/acmesolver
