ADD https://raw.githubusercontent.com/prometheus-community/postgres_exporter/master/LICENSE /opt/bitnami/postgres-exporter/licenses/LICENSE
COPY --link --from=postgres-exporter /bin/postgres_exporter /opt/bitnami/postgres-exporter/bin/
