ADD https://raw.githubusercontent.com/minio/mc/master/LICENSE /opt/bitnami/minio-client/licenses/LICENSE
COPY --from=minio-client /bin/mc /opt/bitnami/minio-client/bin/mc

RUN ln -s /opt/bitnami/minio/bin/mc /opt/bitnami/minio/bin/minio-client
