FROM docker.io/bitnami/minideb:bullseye AS etcd
RUN apt update && apt install -y ca-certificates curl gzip libc6 procps tar wget && \
    cd /tmp && \
    wget -nc -P /tmp/ https://github.com/etcd-io/etcd/releases/download/v{{{VERSION}}}/etcd-v{{{VERSION}}}-linux-$(dpkg --print-architecture).tar.gz && \
    tar -zxf /tmp/etcd-v{{{VERSION}}}-linux-$(dpkg --print-architecture).tar.gz && \
    mv etcd-v{{{VERSION}}}-linux-$(dpkg --print-architecture)/etcd* /usr/local/bin && \
    rm -rf /tmp/*.tar.gz
