ARG TARGETARCH 
FROM docker.io/bitnami/minideb:buster AS etcd
RUN apt update && apt install -y ca-certificates curl gzip libc6 procps tar wget && \
    cd /tmp && \
    wget -nc -P /tmp/ https://github.com/etcd-io/etcd/releases/download/v{{{VERSION}}}/etcd-v{{{VERSION}}}-linux-${TARGETARCH:-amd64}.tar.gz && \
    tar -zxf /tmp/etcd-v{{{VERSION}}}-linux-${TARGETARCH:-amd64}.tar.gz && \
    mv etcd-v{{{VERSION}}}-linux-${TARGETARCH:-amd64}/etcd* /usr/local/bin && \
    rm -rf /tmp/*.tar.gz
